apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/dgozalo/python-repo:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/dgozalo/python-repo:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: python-repo
        chartPath: charts/python-repo
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/dgozalo/python-repo'
          image.tag: '{{.DIGEST_HEX}}'
